### ISSUE TITLE
Sockeye: Afraz to update latest "environment.yml"

### ISSUE THREAD

**Issue by lisatwyw** [BCCDC-DSI/RADD#39]
Hi Afraz,

On Sockeye, could you pls load your ```rds2py``` environment and issue the following?

```
conda env export | grep -v "^prefix: " > environment.yml
```

Next, commit the new version of ```environment.yml``` to our shared repository?

That way, Aaron could reproduce your Python environment as:
```
conda env create -f environment.yml
```

Thanks!
Lisa

**Comment by Afraz496** [comment]
Hi Lisa

I am currently loading in a blank conda environment and then manually installing a requirements.txt

I can document these steps and update this issue.

**Comment by lisatwyw** [comment]
openpyxl==3.1.5 # adding this package to allow export to Excel
