### ISSUE TITLE
Afraz to finalize results of Part 2

### ISSUE THREAD

**Issue by lisatwyw** [BCCDC-DSI/RADD#41]
Hello Afraz,

Thanks for your updates shared on Teams regarding Part 2:

```
...
 
using the x500r trained model the tables are available on /scratch/st-ashapi01-1/RADD/SMILES_ML_PIPELINE/X500R_output
 
There are 2 files:
db_long.csv: The X500R database          # <-- performance on the development set  
test_db_long.csv: The NPS database      # <-- performance on the test set 

Note that this is using X500R models only
```

I have added the comments above. I think you had to trim the SMILES of the samples in the test set. Please correct me if otherwise. 

Q: could you also generate the results for the opposite case? 

i.e. /scratch/st-ashapi01-1/RADD/SMILES_ML_PIPELINE/NPS_output  ?

Here, could you fit with a very large value for MAX_LENGTH so that you won't have to trim during test time this time? 

Thanks!
Lisa

**Comment by lisatwyw** [comment]
See my comment to your earlier issue:
https://github.com/BCCDC-DSI/RADD/issues/24#issuecomment-2229920117

**Comment by lisatwyw** [comment]
Questions:

1) In sbatch code below, ***DATA_PATH*** is the data being used to fit the models???
2) To test the models on new cohort, we run ***generate_model_stats.py***?

```
models.py   # keep
create_dataset.py    # <-- obsolete ? 
generate_model_stats.py  
train.py   # <-- delete?
test.py    # <-- delete?
train_test.py  # <-- keep
```


```
#!/bin/sh
#SBATCH --job-name=ml_pipeline         # Job name
#SBATCH --account=st-ashapi01-1        # Specify your allocation code
#SBATCH --job-name=smiles_ml_pipeline  # Specify the job name
#SBATCH --ntasks=8                     # Number of tasks (processes)
#SBATCH --nodes=1                      # Number of nodes
#SBATCH --time=140:00:00               # Time limit hrs:min:sec
#SBATCH --mem=8G                       # Memory limit
#SBATCH --array=1-5                    # Job array
#SBATCH --output=logs/array_%A_%a.out  # Redirects standard output to unique files for each sub-job.
#SBATCH --error=logs/array_%A_%a.err   # Redirects standard error to unique files for each sub-job.
#SBATCH --partition=skylake            # Partition name

# Define variables for file paths
SCRIPT_PATH="/arc/project/st-ashapi01-1/git/RADD/workflows/part2_version2/train_test.py"
OUTPUT_PATH="/scratch/st-ashapi01-1/RADD/SMILES_ML_PIPELINE/NPS_OUTPUT"
DATA_PATH="/arc/project/st-ashapi01-1/git/RADD/workflows/part2_version2/Data/training_data_bccdc_20240708.csv"

# Print the date and time
echo "Job started at: $(date)"

# Run the Python script with specified arguments
python $SCRIPT_PATH -o $OUTPUT_PATH -d $DATA_PATH

# Print the date and time
echo "Job finished at: $(date)"
```

**Comment by Afraz496** [comment]
Yes to test it on new databases we run `generate_model_stats.py` (this presumes you have at least 2 trained models + data on compound databases)

To address, I would suggest keeping `create_dataset.py` as that directly takes the Compound input then it applies my `PubChem` algorithm to it to generate the SMILES data which is the input to the pipeline.

Other files like `train.py` and `test.py` directly feed into `train_test.py` so it makes the code more modular.

`DATA_PATH` is the path to the dataset the model was trained on (this must be the same data used for `-m` in `generate_model_stats.py`)

**Comment by Afraz496** [comment]
Made a modification to `SMILESVectorizer()`:

```
def transform(self, smiles):
        embed_length = self.max_smiles_length + 2  # Add 2 for start ('!') and end ('E') characters
        one_hot = np.zeros((len(smiles), embed_length, self.charset_size), dtype=np.uint8)
        for i, smile in enumerate(smiles):
            one_hot[i, 0, self.char_to_int["!"]] = 1  # encode start character
            for j, c in enumerate(smile):
                if j + 1 < embed_length - 1:  # ensure within bounds
                    if c in self.char_to_int:
                        one_hot[i, j + 1, self.char_to_int[c]] = 1
                    else:
                        one_hot[i, j + 1, self.char_to_int['UNK']] = 1
            one_hot[i, min(len(smile) + 1, embed_length - 1), self.char_to_int["E"]] = 1  # encode end character
        return one_hot[:, 0:-1, :], one_hot[:, 1:, :]
```

The transform method now understands the bounds it can transform on which prevents out of index errors (this is trimming the larger dataset)

Also note the results of part 2 are available under:

1. `/scratch/st-ashapi01-1/RADD/SMILES_ML_PIPELINE/NPS_OUTPUT`
2. `/scratch/st-ashapi01-1/RADD/SMILES_ML_PIPELINE/X500R_output`

The files of interest are:

1. `error_db.png`: Error bins for the Dataset the model was trained on
2. `error_test_db.png`: Error bins for the Dataset the model is deployed on
3. `db_long.csv`: Excel format table for the error of the dataset them model was trained on
4. `test_db_long.csv`: Excel format table for the error of the dataset the model was deployed on

Adding a documentation step to the `summary` branch for the Consult.
